name: Kappa
channels:
    - conda-forge
dependencies:
    - python=3.10.6
    - numpy=1.23.2
    - scipy=1.9.1
    - matplotlib=3.5.3
    - pandas=1.4.3
    - sympy=1.10.1
    - jupyterlab=3.4.5
    - notebook=6.4.12
    - ipywidgets=8.0.1
    - tifffile=2022.8.12
    - tqdm=4.64.0
    - scikit-image=0.19.3
    - pyimagej=1.2.1
    - pillow=9.2.0
    - joblib=1.1.0
